### ISSUE TITLE
Xiaomi scooters

### ISSUE THREAD

**Issue by RiccardoCestaro** [dnandha/miauth#1]
Hello!
Actually, I'm trying to connect my Xiaomi Scooter m365 using 55AB protocol from Xiaomi but there are some problems. For example in the authentication phase there isn't any AVDTP uuid available from the scooter. 
How I can solve this uuid problem?

**Comment by dnandha** [comment]
Hi @RiccardoCestaro ,
thanks for testing the lib first of all!

The m365 does not use the Mi EC protocol, this is also why the GATT services you mentioned are missing.

You can try using the Nb Protocol, chances are it might work. For this just run miauth with the `--nb` flag. Btw, I just pushed a fix for the miauth cli so that this flag is correctly parsed. Either update your package through pip or pull the latest commits from this repo.

Best - D

**Comment by RiccardoCestaro** [comment]
Thanks!!
I confirm that using 5AA5 works well.

Regards

**Comment by RiccardoCestaro** [comment]
only a question: where came from the FW_DATA? How did you find it?

**Comment by dnandha** [comment]
@RiccardoCestaro Hey Riccardo, good question! Like stated in the file header my NB lib is based on [https://github.com/scooterhacking/NinebotCrypto](https://github.com/scooterhacking/NinebotCrypto). There you'll also find the FW_DATA.
